---
title: "Megan Caton Ferguson, Ph.D."
subtitle: "Curriculum Vitae"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

meganferg@gmail.com

I am a Research Fisheries Biologist at NOAA Fisheries’ Marine Mammal Laboratory, located at the Alaska Fisheries Science Center in Seattle, Washington. Since 2008, I have focused on Arctic cetacean research, conservation, management, and policy. Quantitative ecology and decision-making form the core of my research interests. When I am not in the office or the field, I am with my dog, walking rescue dogs, or in the eye of a chalk dust storm at the CrossFit gym.

## Research Interests  
●	Applying statistical and mathematical models to natural resource conservation and management issues, including stock assessments and ecosystem-based management  
●	Investigating ecological patterns and processes in space and time over scales ranging from kilometers to thousands of kilometers, hours to decades, and individuals to ecosystems  
●	Applying a multidisciplinary approach, including co-production of scientific and Indigenous knowledge, to further understanding into the biological, physical, and chemical mechanisms that drive spatiotemporal variability in dynamic ecosystems  
 
## Education  

●	M.S., Quantitative Ecology and Resource Management, University of Washington, Seattle, 2022  
●	Ph.D., Oceanography, Scripps Institution of Oceanography, University of California, San Diego, 2005  
●	B.S., Zoology, University of Washington, Seattle, 1997  
●	B.S., Fisheries, University of Washington, Seattle, 1997    


## Certifications and Membership in Professional Societies  
●	Underwater Egress and HEEDS: re-certified 29 March 2022  
●	Pet CPR and First Aid: certified 20 March 2022  
●	Wilderness First Aid: re-certified 7 February 2022  
●	CPR and AED: re-certified 17 November 2021  
●	Federal Aviation Safety Officer, Interagency Committee for Aviation Policy: re-certified January 2018  
●	Scholarly Union of BioPhysical Arctic Researchers  
●	Ancient Order of the Deep    



## Select Journal Articles and Reports  
**Ferguson**, M.C. 2005. Cetacean population density in the eastern Pacific Ocean: Analyzing patterns with predictive spatial models. University of California San Diego, Scripps Institution of Oceanography, PhD Dissertation, 221pp. [pdf](https://github.com/megancatonferguson/MCF_CV/blob/main/pdfs/Ferguson2005dissertation.pdf)  

**Ferguson**, M.C. 2012. Quantifying spatial characteristics of the Bowhead Whale Aerial Survey Project (BWASP) survey design. Journal of Cetacean Research and Management 12(1):39-44 https://doi.org/10.47536/jcrm.v12i1.589  

**Ferguson**, M.C. 2022. Spatial modeling, parameter uncertainty, and precision of density estimates from line-transect surveys: a case study with Western Arctic bowhead whales. University of Washington, MS Thesis, 66 + xii pp. http://hdl.handle.net/1773/48556    

**Ferguson**, M.C., R.P. Angliss, A. Kennedy, B. Lynch, A. Willoughby, V. Helker, A.A. Brower, and J.T. Clarke. 2018. Performance of manned and unmanned aerial surveys to collect visual data and imagery for estimating arctic cetacean density and associated uncertainty. Journal of Unmanned Vehicle Systems 6(3):128-154. 
https://doi.org/10.1139/juvs-2018-0002  

**Ferguson**, M.C., J. Barlow, P. Fiedler, S.B. Reilly, and T. Gerrodette. 2006. Spatial models of delphinid (family Delphinidae) encounter rate and group size in the eastern tropical Pacific Ocean. Ecological Modelling 193: 645-662. https://doi.org/10.1016/j.ecolmodel.2005.10.034

**Ferguson**, M.C., J. Barlow, S.B. Reilly, and T. Gerrodette. 2006. Predicting Cuvier's (Ziphius cavirostris) and Mesoplodon beaked whale population density from habitat characteristics in the eastern tropical Pacific Ocean. Journal of Cetacean Research and Management 7(3): 287-299. https://doi.org/10.47536/jcrm.v7i3.738  

**Ferguson**, M.C., J.T. Clarke, R. Angliss, J. Bengtson, A. Brower, J. Citta, P.J. Clapham, P. Conn, K.A. Forney, J.C. George, and G.H. Givens. 2018. Bering-Chukchi-Beaufort bowhead whale abundance estimation survey workshop report. Paper SC/67b/AWMP16 presented to the IWC Scientific Committee, May 2018. [pdf](https://github.com/megancatonferguson/MCF_CV/blob/main/pdfs/SC_67B_AWMP_16.pdf)  

**Ferguson**, M.C., J.T. Clarke, A.A. Brower, A.L. Willoughby, and S.R. Okkonen. 2021. Ecological variation in the western Beaufort Sea. In: J.C. George and J.G.M. Thewissen (Eds.), The Bowhead Whale Balaena mysticetus: biology and human interactions. Academic Press, pp. 365-379.  

**Ferguson**, M.C., J. T. Clarke, A. L. Willoughby, A. A. Brower, and A. D. Rotrock. 2021. Geographically stratified abundance estimate for Bering-Chukchi-Beaufort Seas bowhead whales (Balaena mysticetus) from an August 2019 aerial line-transect survey in the Beaufort Sea and Amundsen Gulf. U.S. Dep. Commer., NOAA Technical Memorandum NMFS-AFSC-428, 54 p. [pdf](https://repository.library.noaa.gov/view/noaa/33451) 

**Ferguson**, M.C., C. Curtice, and J. Harrison. 2015. Biologically Important Areas for cetaceans within U.S. waters: Gulf of Alaska region. Aquatic Mammals 41(1): 65-78. http://dx.doi.org/10.1578/AM.41.1.2015.1  

**Ferguson**, M.C., C. Curtice, J. Harrison, and S.M. Van Parijs. 2015. Biologically Important Areas for marine mammals within U.S. waters: Overview and rationale. Aquatic Mammals 41(1):2-16. http://dx.doi.org/10.1578/AM.41.1.2015.1 

**Ferguson**, M.C., D.L. Miller, J.T. Clarke, A.A. Brower, A.L. Willoughby, and A.D. Rotrock. 2022. Spatial modeling, parameter uncertainty, and precision of density estimates from line-transect surveys: a case study with Western Arctic bowhead whales. Paper SC/68d/ASI/01 presented to the IWC Scientific Committee, May 2022. [pdf](https://github.com/megancatonferguson/MCF_CV/blob/main/pdfs/SC_68D_ASI_01.pdf)

**Ferguson**, M.C., S.F. Tóth, J.T. Clarke, A.L. Willoughby, A.A. Brower, and T.P. White. 2023. Biologically Important Areas for Bowhead Whales (Balaena mysticetus): Optimal site selection with integer programming. Frontiers in Marine Science 10: 961163. https://www.frontiersin.org/articles/10.3389/fmars.2023.961163/full 

**Ferguson**, M.C., J. Waite, C. Curtice, J.T. Clarke, and J. Harrison. 2015. Biologically Important Areas for cetaceans within U.S. waters: Aleutian Islands and Bering Sea region. Aquatic Mammals 41(1):79-93. http://dx.doi.org/10.1578/AM.41.1.2015.1 

Angliss, R.P., M.C. **Ferguson**, P. Hall, V. Helker, A. Kennedy, and T. Sformo. 2018. Comparing manned aerial surveys to unmanned aerial surveys for cetacean monitoring in the Arctic: Operational results and recommendations. Journal of Unmanned Vehicle Systems 6(3): 109-127. https://cdnsciencepub.com/doi/10.1139/juvs-2018-0001  

Blackwell, S.B., A.M. Thode, A.S. Conrad, M.C. **Ferguson**, C.L. Berchok, K.M. Stafford, T.A. Marques, and K.H. Kim. Estimating acoustic cue rates in bowhead whales, Balaena mysticetus, during their fall migration through the Alaskan Beaufort Sea. 2021. Journal of the Acoustical Society of America 149(5): 3611-3625. https://doi.org/10.1121/10.0005043  

Brower, A.B., J.T. Clarke, M.C. **Ferguson**. 2018. Increased Sightings of SubArctic Cetaceans in the Eastern Chukchi Sea, 2008-2016: population recovery, response to climate change, or increased effort? Polar Biology. https://doi.org/10.1007/s00300-018-2257-x  

Brower A., M. **Ferguson**, J. Clarke, E. Fujioka, and S. DeLand. 2022. Biologically Important Areas II for cetaceans within U.S. and adjacent waters – Aleutian Islands and Bering Sea region. Frontiers in Marine Science 9:1055398. https://doi.org/10.3389/fmars.2022.1055398  

Brower, A., M. **Ferguson**, S. Schonberg, S. Jewett, and J. Clarke. 2017. Gray whale distribution relative to benthic invertebrate biomass and abundance: northeastern Chukchi Sea, 2009-2012. Deep-Sea Research II 144: 156-174. https://doi.org/10.1016/j.dsr2.2016.12.007.  

Brower, A., M. **Ferguson**, and A. Willoughby. 2022. Bowhead whale distribution and relative density in relation to remote-sensed physical and biological environmental data in the Pacific Arctic, 2014-2019. U.S. Department of Commerce, Technical Memorandum NMFS-AFSC-438. 234 p. [pdf](https://repository.library.noaa.gov/view/noaa/43044) 

Brower, A., A. Willoughby, and M. **Ferguson**. 2022. Distribution and relative abundance of bowhead whales and other marine mammals in the western Beaufort Sea, 2020. U.S. Department of Commerce, NOAA Technical Memorandum NMFS-AFSC-439. 155 p. [pdf](https://repository.library.noaa.gov/view/noaa/44403) 

Brower, A.A., A.L. Willoughby, K.A. Scheimreif, and M.C. **Ferguson**. 2022. Distribution and relative abundance of bowhead whales and other marine mammals in the western Beaufort Sea, 2021. U.S. Department of Commerce, NOAA Technical Memorandum NMFS-AFSC-455, 201 p. [pdf](https://repository.library.noaa.gov/view/noaa/47924) 

Calambokidis, J., G. Steiger, C. Curtice, J. Harrison, M.C. **Ferguson**, E. Becker, M. DeAngelis, and S.M. Van Parijs. 2015. Biologically Important Areas for cetaceans within U.S. waters: West Coast region. Aquatic Mammals 41(1): 39-53. http://dx.doi.org/10.1578/AM.41.1.2015.1  

Castellote, M., A. Mooney, R. Andrews, S. Deruiter, W. Lee, M. **Ferguson**, and P. Wade. 2021. Beluga whale (Delphinapterus leucas) acoustic foraging behavior and applications for long term monitoring. PlosONE 16(11): e0260485. https://doi.org/10.1371/journal.pone.0260485  

Christman, C., J. Citta, L. Quakenbush, J. Clarke, B. Rone, R. Shea, M. **Ferguson** and M. Heide-Jørgensen. 2013. Presence and behavior of bowhead whales (Balaena mysticetus) in the Alaskan Beaufort Sea in July 2011. Polar Biology 36(12): 1851-1856. https://doi.org/10.1007/s00300-013-1395-4  

Clarke, J., A. Brower, C. Christman, and M. **Ferguson**. 2014. Distribution and relative abundance of marine mammals in the northeastern Chukchi and western Beaufort Seas, 2013. Annual report, OCS Study BOEM 2014-0018. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC, Seattle, WA 98115-6349. 330 pp. [pdf](https://www.fisheries.noaa.gov/resource/data/2013-aerial-surveys-arctic-marine-mammals)  

Clarke, J.T., A.A. Brower, M.C. **Ferguson**, and A.S. Kennedy. 2015. Distribution and relative abundance of marine mammals in the eastern Chukchi and western Beaufort seas, 2014. Annual Report, OCS Study BOEM 2015-040. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2014-aerial-surveys-arctic-marine-mammals) 

Clarke, J.T., A.A. Brower, M.C. **Ferguson**, and A.L. Willoughby. 2017. Distribution and Relative Abundance of Marine Mammals in the Eastern Chukchi and Western Beaufort Seas, 2015. Annual Report, OCS Study BOEM 2017-019. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2015-aerial-surveys-arctic-marine-mammals)  

Clarke, J.T., A.A. Brower, M.C. **Ferguson**, and A.L. Willoughby. 2017. Distribution and Relative Abundance of Marine Mammals in the Eastern Chukchi and Western Beaufort Seas, 2016.  Annual Report, OCS Study BOEM 2017-078.  Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2016-aerial-surveys-arctic-marine-mammals) 

Clarke, J.T., A.A. Brower, M.C. **Ferguson**, and A.L. Willoughby. 2018. Distribution and Relative Abundance of Marine Mammals in the Eastern Chukchi and Western Beaufort Seas, 2017. Annual Report, OCS Study BOEM 2018-023. Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2017-aerial-surveys-arctic-marine-mammals) 

Clarke, J.T., A.A. Brower, M.C. **Ferguson**, and A.L. Willoughby. 2019. Distribution and Relative Abundance of Marine Mammals in the Eastern Chukchi and Western Beaufort Seas, 2018. Annual Report, OCS Study BOEM 2019-021. Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2018-aerial-surveys-arctic-marine-mammals) 

Clarke, J.T., A.A. Brower, M.C. **Ferguson**, A.L. Willoughby, and A.D. Rotrock. 2020. Distribution and Relative Abundance of Marine Mammals in the Eastern Chukchi Sea, Eastern and Western Beaufort Sea, and Amundsen Gulf, 2019. Annual Report, OCS Study BOEM 2020-027. Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2019-aerial-surveys-arctic-marine-mammals)  

Clarke, J.T., C.L. Christman, A.A. Brower, and M.C. **Ferguson**. 2012. Distribution and relative abundance of marine mammals in the Alaskan Chukchi and Beaufort seas, 2011. Annual Report, OCS Study BOEM 2012-009. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2011-aerial-surveys-arctic-marine-mammals) 

Clarke, J.T., C.L. Christman, A.A. Brower, and M.C. **Ferguson**. 2013. Distribution and relative abundance of marine mammals in the northeastern Chukchi and western Beaufort seas, 2012. Annual Report, OCS Study BOEM 2013-00117. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2012-aerial-surveys-arctic-marine-mammals)  

Clarke, J., C. Christman, A.A. Brower, M.C. **Ferguson**, and S.L. Grassia. 2011. Aerial surveys of endangered whales in the Beaufort Sea, fall 2010. Annual report, OCS Study BOEMRE 2011-035. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC, Seattle, WA 98115-6349. 119 pp. [pdf](https://www.fisheries.noaa.gov/resource/data/2010-aerial-surveys-endangered-whales-beaufort-sea)  

Clarke, J.T., C.L. Christman, M.C. **Ferguson**, and S.L. Grassia. 2011. Aerial surveys of endangered whales in the Beaufort Sea, fall 2006-2008. Final Report, OCS Study BOEMRE 2011-033. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2006-2008-aerial-surveys-endangered-whales-beaufort-sea)  

Clarke, J.T., C.L. Christman, S.L. Grassia, A.A. Brower, and M.C. **Ferguson**. 2011. Aerial surveys of endangered whales in the Beaufort Sea, fall 2009. Final Report, OCS Study BOEMRE 2011-040. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2009-aerial-surveys-endangered-whales-beaufort-sea)  

Clarke, J.T., M.C. **Ferguson**, A.A. Brower, E. Fujioka, and S. DeLand. 2023. Biologically Important Areas II for cetaceans in U.S. and adjacent waters – Arctic region. Frontiers in Marine Science 10:1040123. https://doi.org/10.3389/fmars.2023.1040123

Clarke, J.T., M.C. **Ferguson**, C.L. Christman, S.L. Grassia, A.A. Brower, and L.J. Morse. 2011. Chukchi Offshore Monitoring in Drilling Area (COMIDA) distribution and relative abundance of marine mammals: aerial surveys. Final Report, OCS Study BOEMRE 2011-06. National Marine Mammal Laboratory, Alaska Fisheries Science Center, NMFS, NOAA, 7600 Sand Point Way NE, F/AKC3, Seattle, WA 98115-6349. [pdf](https://www.fisheries.noaa.gov/resource/data/2008-2010-chukchi-offshore-monitoring-drilling-area-distribution-and-relative)  

Clarke, J.T., M.C. **Ferguson**, C. Curtice, and J. Harrison. 2015. Biologically Important Areas for cetaceans within the U.S. waters: Arctic region. Aquatic Mammals 41(1):94-103. http://dx.doi.org/10.1578/AM.41.1.2015.1  

Clarke, J.T., M.C. **Ferguson**, S.R. Okkonen, A.A. Brower, and A.L. Willoughby. 2022. Bowhead whale calf detections in the western Beaufort sea during the open water season, 2012–2019. Arctic Science. https://doi.org/10.1139/as-2021-0020

Clarke, J.T., M.C. **Ferguson**, A.L. Willoughby, and A.A. Brower. 2018. Bowhead whale and beluga distributions, sighting rates, and habitat associations in the western Beaufort Sea, summer and fall 2009-2016, with a retrospective comparison to 1982-1991. Arctic 71(2):115-138. https://www.jstor.org/stable/26478010 

Clarke, J.T., A.S. Kennedy, and M.C. **Ferguson**. 2016. Bowhead and Gray Whale Distributions, Sighting Rates, and Habitat Associations in the Eastern Chukchi Sea, Summer and Fall 2009-2015, with a Retrospective Comparison to 1982-1991. Arctic 69(4):359-377. https://www.jstor.org/stable/24878034  

Douglas, A.B., J. Calambokidis, L.M. Munger, M.S. Soldevilla, M.C. **Ferguson**, A.M. Havron, D.L. Camacho, G.S. Campbell, and J.A. Hildebrand. 2014. Seasonal distribution and abundance of cetaceans off Southern California estimated from CalCOFI cruise data from 2004 to 2008. Fishery Bulletin 112: 197-220. DOI 10.7755/FB.112.2-3.7.  

Druckenmiller, M.L., J.J. Citta, M.C. **Ferguson**, J.T. Clarke, J.C. George, and L. Quakenbush. 2018. Trends in sea ice cover within bowhead whale use areas in the Pacific Arctic. Deep-Sea Research II 152:95-107. https://doi.org/10.1016/j.dsr2.2017.10.017.  

Forney, K.A., M.C. **Ferguson**, E.A. Becker, P.C. Fiedler, J.V. Redfern, J. Barlow, I.L. Vilchis, and L.T. Ballance. 2012. Habitat-based spatial models of cetacean density in the eastern Pacific Ocean. Endangered Species Research 16:113-133.  

Gedamke, J., M. **Ferguson**, J. Harrison, L. Hatch, L. Henderson, M.B. Porter, L. Southall, and S. Van Parijs. 2016. Predicting anthropogenic noise contributions to US waters. p. 341-347 In: Popper, A. N.and Hawkins, A., eds., Effects of noise on aquatic life II.  Berlin, Springer-Verlag.  

George, J.C, R. Stimmelmayr, A, Brower, J. Clarke, M. **Ferguson**, A. Von Duyke, G. Sheffield, K. Stafford, T. Sformo, B. Person, L. Sousa, B. Tudor, and R. Suydam. 2017a. 2016 Health report for the Bering – Chukchi - Beaufort Seas bowhead whales – Preliminary findings. Paper SC/67A/AWMP/10 presented to the IWC Scientific Committee, May 2017.  

Givens GH, M.C. **Ferguson**, J.T. Clarke, A. Willoughby, A. Brower, and R. Suydam. 2020. Abundance of the Eastern Chukchi Sea Stock of Beluga Whales, 2012-2017. Arctic 73(4):485-498. DOI 10.14430/arctic71592.  

Halliday, W.D., N. Le Baron, J.J. Citta, J. Dawson, T. Doniol-Valcroze, M. **Ferguson**, S.H. Ferguson, S. Fortune, L.A. Harwood, M.P. Heide-Jørgensen, E.V. Lea, L. Quakenbush, B.G. Young, D. Yurkowski, and S.J. Insley. 2022. Overlap between bowhead whales (Balaena mysticetus) and vessel traffic in the North American Arctic and implications for conservation and management. Biological Conservation 276: 109820. DOI 10.1016/j.biocon.2022.109820.  

Harrison, J., M. **Ferguson**, J. Gedamke, L. Hatch, B. Southall, and S. Van Parijs. 2016. National Oceanic and Atmospheric Administration’s Cetacean and Sound Mapping Effort: Continuing forward with an integrated ocean noise strategy. p. 409-416 In: Popper, A. N.and Hawkins, A., eds., Effects of noise on aquatic life II.  Berlin, Springer-Verlag.  

Harrison, J., M.C. **Ferguson**, L. New, J. Cleary, C. Curtice, S. DeLand, E. Fujioka, P.N. Halpin, R.B. Tyson Moore, and S.M. Van Parijs. 2023. Biologically Important Areas II for cetaceans within U.S. and adjacent waters – Updates and the application of a new scoring system. Frontiers in Marine Science 10:1081893. DOI 10.3389/fmars.2023.1081893.  

Joyce, T., M. **Ferguson**, C. Berchok, D. Wright, J. Crance, E. Braen, T. Eguchi, W.L. Perryman, and D. Weller. 2023. The role of sea ice in the distribution, habitat use, and phenology of eastern North Pacific gray whales. Marine Ecology Progress Series 709: 141-158. DOI 10.3354/meps14271.  

Kuletz, K.J., M.C. **Ferguson**, B. Hurley, A.E. Gall, E.A. Labunski, and T.C. Morgan. 2015. Seasonal spatial patterns in seabird and marine mammal distribution in the eastern Chukchi and western Beaufort seas: Identifying biologically important pelagic areas. Progress in Oceanography. DOI 10.1016/j.pocean.2015.05.012  

Laake, J.L., A.E. Punt, R. Hobbs, M. **Ferguson**, D. Rugh, and J. Breiwick. 2012. Gray whale southbound migration surveys 1967-2006: an integrated re-analysis. Journal of Cetacean Research and Management 12(3):287-306.  

Mannocci, L., A.M. Boustany, J.J. Roberts, D.M. Palacios, D.C. Dunn, P.N. Halpin, S. Viehman, J. Moxley, J. Cleary, H. Bailey, S.J. Bograd, E.A. Becker, B. Gardner, J.R. Hartog, E.L. Hazen, M.C. **Ferguson**, K.A. Forney, B.P. Kinlan, M.J. Oliver, C.T. Perretti, V. Ridoux, S.L.H. Teo, and A.J. Winship. 2017. Temporal resolutions in species distribution models of highly mobile marine animals: Recommendations for ecologists and managers. Diversity and Distributions 23:1098-1109. 10.1111/ddi.12609.  

Mayette, A., M. Marcoux, J. Iacozza, M. **Ferguson**, A. Brower, and L. Loseto. Paper in press. Summer distribution and habitat preference of beluga whale social groups in the Eastern Beaufort Sea. Arctic Science. DOI 10.1139/as-2022-0035.  

Muto, M.M., V.T. Helker, R.P. Angliss, P.L. Boveng, J.M. Breiwick, M.F. Cameron, P.J. Clapham, S.P. Dahle, M.E. Dahlheim, B.S. Fadely, M.C. **Ferguson**, L.W. Fritz, R.C. Hobbs, Y.V. Ivashchenko, A.S. Kennedy, J.M. London, S.A. Mizroch, R.R. Ream, E.L. Richmond, K.E.W. Shelden, K.L. Sweeney, R.G. Towell, P.R. Wade, J.M. Waite, and A.N. Zerbini. 2019. Alaska marine mammal stock assessments, 2018. U.S. Department of  Commerce, NOAA Tech. Memo. NMFS-AFSC-393, 390 p.  

Muto, M.M., V.T. Helker, R.P. Angliss, B.A. Allen, P.L. Boveng, J.M. Breiwick, M.F. Cameron, P.J., Clapham, S.P Dahle, M.E. Dahlheim, B.S. Fadely, M.C. **Ferguson**, L.W. Fritz, R.C. Hobbs, Y.V. Ivashchenko, A.S. Kennedy, J.M. London, S.A. Mizroch, R.R. Ream, E.L. Richmond, K.E.W. Shelden, R.G. Towell, P.R. Wade, J.M. Waite, and A.N. Zerbini. 2016. Alaska marine mammal stock assessments, 2015. US Department of Commerce, NOAA Technical Memorandum NMFS-AFSC-323, 300 p. doi: 10.7289/V5/TM-AFSC-323.  

Muto, M.M., V.T. Helker, R.P. Angliss, B.A. Allen, P.L. Boveng, J.M. Breiwick, M.F. Cameron, P.J., Clapham, S.P Dahle, M.E. Dahlheim, B.S. Fadely, M.C. **Ferguson**, L.W. Fritz, R.C. Hobbs, Y.V. Ivashchenko, A.S. Kennedy, J.M. London, S.A. Mizroch, R.R. Ream, E.L. Richmond, K.E.W. Shelden, R.G. Towell, P.R. Wade, J.M. Waite, and A.N. Zerbini. 2017. Alaska marine mammal stock assessments, 2016. US Department of Commerce, NOAA Technical Memorandum NMFS-AFSC-355, 366 p. doi: 10.7289/V5/TM-AFSC-355.  

Muto, M.M., V. T. Helker, R. P. Angliss, B. A. Allen, P. L. Boveng,J. M. Breiwick, M. F. Cameron, P. J. Clapham, S. P. Dahle,M. E. Dahlheim, B. S. Fadely, M.C. **Ferguson**, L. W. Fritz, R. C. Hobbs, Y. V. Ivashchenko, A. S. Kennedy, J. M. London, S. A. Mizroch, R. R. Ream, E. L. Richmond, K. E. W. Shelden, R. G. Towell,P. R. Wade, J.M. Waite, and A.N. Zerbini. 2018. Alaska marine mammal stock assessments, 2017. U.S. Dep. Commer., NOAA Tech. Memo. NMFS-AFSC-378, 382 p.  

Muto, M.M., V.T. Helker, B.J. Delean, R.P. Angliss, P.L. Boveng, J.M. Breiwick, B.M. Brost, M.F. Cameron, P.J. Clapham, S.P. Dahle, M.E. Dahlheim, B.S. Fadely, M.C. **Ferguson**, L.W. Fritz, R.C. Hobbs, Y.V. Ivashchenko, A.S. Kennedy, J.M. London, S.A. Mizroch, R.R. Ream, E.L. Richmond, K.E.W. Shelden, K.L. Sweeney, R.G. Towell, P.R. Wade, J.M. Waite, and A.N. Zerbini. 2020. Alaska marine mammal stock assessments, 2019. U.S. Department of Commerce, NOAA Tech. Memo. NMFS-AFSC-404, 395 p.  

Muto, M.M., V.T. Helker, B.J. Delean, N.C. Young, J.C. Freed, R.P. Angliss, N.A. Friday, P.L. Boveng, J.M. Breiwick, B.M. Brost, M.F. Cameron, P.J. Clapham, J.L. Crance, S.P. Dahle, M.E. Dahlheim, B.S. Fadely, M.C. **Ferguson**, L.W. Fritz, K.T. Goetz, R.C. Hobbs, Y.V. Ivashchenko, A.S. Kennedy, J.M. London, S.A. Mizroch, R.R. Ream, E.L. Richmond, K.E.W. Shelden, K.L. Sweeney, R.G. Towell, P.R. Wade, J.M. Waite, and A.N. Zerbini. 2021. Alaska marine mammal stock assessments, 2020. U.S. Dep. Commer., NOAA Tech. Memo. NMFS-AFSC-421, 398 p.  

Soldevilla, M.S., S.M. Wiggins, J.A. Hildebrand, E.M. Oleson, and M.C. **Ferguson**. 2011. Risso’s and Pacific white-sided dolphin habitat modeling from passive acoustic monitoring. Marine Ecology Progress Series 423: 247-260.  

Stafford, K. M., E.V. Farley, M. **Ferguson**, K.J. Kuletz, and R. Levine. 2022. Northward Range Expansion of Subarctic Upper Trophic Level Animals into the Pacific Arctic Region. Oceanography. DOI 10.5670/oceanog.2022.101.  

Stafford, K.M., M.C. **Ferguson**, D.D.W. Hauser, S.R. Okkonen, C.L. Berchok, J.J. Citta, J.T. Clarke, E.C. Garland, J. Jones, and R.S. Suydam. 2016. Beluga whales in the western Beaufort Sea: Current state of knowledge on timing, distribution, habitat use and environmental drivers. Deep Sea Research II: Topical Studies in Oceanography 152: 182-194. DOI 10.1016/j.dsr2.2016.11.017.  

Stimmelmayr, R., J. Citta, K. Scheimreif, M. **Ferguson**, G.H. Givens, A. Willoughby, A. Brower, A. Von Duyke, G. Sheffield, B. Person, T. Sformo, L. de Sousa and R. Suydam. 2022. 2020-2021 Health Report for the Bering-Chukchi-Beaufort Seas Bowhead Whale. Paper SC/68d/ASW/03 presented to the International Whaling Commission Scientific Committee, May 2022.  

Stimmelmayr, R., J.C. George, J. Clarke, M. **Ferguson**, A. Willoughby, A. Brower, G. Sheffield, K. Stafford, G. Givens, A. Von Duyke, T. Sformo, B. Person, L. Sousa, and R. Suydam. 2020. 2018-2019 health report for the Bering-Chukchi-Beaufort Seas bowhead whales – preliminary findings. Paper SC/68b/ASW/03 presented to the International Whaling Commission Scientific Committee, May 2020.  

Stimmelmayr, R., J.C. George, A. Willoughby, A. Brower, J. Clarke, M. **Ferguson**, G. Sheffield, K. Stafford, A. Von Duyke, T. Sformo, B. Person, L. Sousa, and R. Suydam. 2018. 2017 health report for the Bering-Chukchi-Beaufort Seas bowhead whales – preliminary findings. Paper SC/67b/AWMP/08 presented to the IWC Scientific Committee, May 2018.  

Willoughby, A.L., M.C. **Ferguson**, J.T. Clarke, and A.A. Brower. 2018. First photographic match of an anomalously white gray whale (Eschrichtius robustus) in the northeastern Chukchi Sea, Alaska, and Baja California, Mexico. Aquatic Mammals 44(1): 7-12.  

Willoughby, A., M. **Ferguson**, B. Hou, C. Accardo, A. Rotrock, A. Brower, J. Clarke, S. Hanlan, M. Foster Doremus, K. Pagan, and L. Barry. 2021. Belly Port Camera Imagery Collected to Address Cetacean Perception Bias During Aerial Line-Transect Surveys: Methods and Sighting Summaries. U.S. Dep. Commer., NOAA Tech. Memo. NMFS-AFSC-427, 111 p.  

Willoughby, A.L., M.C. **Ferguson**, R. Stimmelmayr, and A.A. Brower. 2022. Bowhead whale (Balaena mysticetus) carcasses documented during the 2019 aerial surveys in the eastern Chukchi and western Beaufort seas: a follow-up to evidence of bowhead whale and killer whale (Orcinus orca) co-occurrence during 2009–2018. Polar Biology. DOI 10.1007/s00300-022-03097-2.  

Willoughby, A.L., M.C. **Ferguson**, R. Stimmelmayr, J.T. Clarke, and A.A. Brower. 2020. Bowhead whale (Balaena mysticetus) and killer whale (Orcinus orca) co-occurrence in the U.S. Pacific Arctic, 2009-2018: evidence from bowhead whale carcasses. Polar Biology 43(11): 1669-1679. DOI 10.1007/s00300-020-02734-y.  

Willoughby, A. L., R. Stimmelmayr, A.A. Brower, J.T. Clarke, and M.C. **Ferguson**. 2022. Gray whale (Eschrichtius robustus) and killer whale (Orcinus orca) co-occurrence in the eastern Chukchi Sea, 2009–2019: evidence from gray whale carcasses observed during aerial surveys. Polar Biology 45:737-748. DOI 10.1007/s00300-022-03015-6.  
